### ISSUE TITLE
On widows  10 it gives this error `Unsupported architecture: windows 10:amd64`

### ISSUE THREAD

**Issue by arkaprovo** [arakelian/java-jq#15]
```
java.lang.IllegalStateException: Unsupported architecture: windows 10:amd64

	at com.arakelian.jq.NativeLib.getPath(NativeLib.java:155)
	at com.arakelian.jq.ImmutableNativeLib.access$1001(ImmutableNativeLib.java:31)
	at com.arakelian.jq.ImmutableNativeLib$InitShim.getPath(ImmutableNativeLib.java:144)
	at com.arakelian.jq.ImmutableNativeLib.<init>(ImmutableNativeLib.java:54)
	at com.arakelian.jq.ImmutableNativeLib.<init>(ImmutableNativeLib.java:31)
	at com.arakelian.jq.ImmutableNativeLib$Builder.build(ImmutableNativeLib.java:510)
	at com.arakelian.jq.JqLibrary.getLoader(JqLibrary.java:242)
	at com.arakelian.jq.ImmutableJqLibrary.getLoader(ImmutableJqLibrary.java:87)
	at com.arakelian.jq.JqLibrary.getJqInit(JqLibrary.java:114)
	at com.arakelian.jq.JqLibrary.jq_init(JqLibrary.java:257)
	at com.arakelian.jq.JqRequest.jq(JqRequest.java:161)
	at com.arakelian.jq.JqRequest.execute(JqRequest.java:58)
```

I have a function like this 

```
private String jqExec(String filter, String payload) {
        JqLibrary library = ImmutableJqLibrary.of();
        final JqRequest request = ImmutableJqRequest
                .builder().lib(library).input(payload)
                .filter(filter).build();
        final JqResponse response = request.execute();
        return response.getOutput();
    }
```
It gets that excption on this line `final JqResponse response = request.execute();`

**Comment by arakelian** [comment]
I'm afraid I don't have the time to add Windows support. This project is not very active. Closing.
